version: '3'
networks:
  traefik:
    external: true

services:
  portfolio:
    build:
      context: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.service=portfolio"
      - "traefik.http.routers.portfolio.rule=Host(`nikolaj-jepsen.dk`)"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
    networks:
      - traefik